name: gcp api deployment


on:
  workflow_run:
    workflows:
      - tests
    types:
      - completed
    branches:
      - master
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to GCP App Engine
        uses: 'google-github-actions/deploy-appengine@v0'
