name: tests

on:
  push:
    paths-ignore:
      - docs/**/*.*
      - README.md
      - .github/workflows/docs.yml
      - .github/workflows/firebase-docs-pr.yml
      - .github/workflows/google-cloud.yml
      - firebase.json
      - .firebaserc
      - .devcontainer/**/*.*
  pull_request:
    types:  # avoid double runs in open pr
      - opened
      - reopened
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Inject keys
        run: echo -en '${{ secrets.KEYS_YAML }}' >> keys.yaml
        
      - name: Remove .dockerignore  # tests folder needed
        run: rm .dockerignore

      - name: Build Docker container
        run: docker build -t jeeves .
        
      - name: Run tests inside container
        run: docker run jeeves sh -c "pip install --no-cache-dir -r tests/requirements.txt && pytest"
